spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: category-route
              uri: lb://category-service
              predicates:
                - Path=/api/categories/**
            - id: product-route
              uri: lb://product-service
              predicates:
                - Path=/api/products/**


server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
